FROM alpine:latest as builder

RUN apk add --no-cache gcc make pcre-dev zlib-dev openssl-dev linux-headers musl-dev curl

ARG NGX_VER=1.30.1

ENV PREFIX /opt/nginx
ENV WORKDIR /src
ENV NGX_SRC_DIR ${WORKDIR}/nginx-${NGX_VER}
ENV NGX_URL http://nginx.org/download/nginx-${NGX_VER}.tar.gz

WORKDIR ${WORKDIR}

RUN tar zxf `curl -SLOs -w'%{filename_effective}' ${NGX_URL}` -C ${WORKDIR}

WORKDIR ${NGX_SRC_DIR}
ADD . traffic-accounting-nginx-module
RUN ./configure --prefix=${PREFIX} \
    --with-stream \
    --add-dynamic-module=traffic-accounting-nginx-module \
    --http-log-path=/dev/stdout \
    --error-log-path=/dev/stderr \
    && make -s && make -s install


FROM alpine:latest

RUN apk add --no-cache pcre zlib tzdata

ENV PREFIX /opt/nginx

COPY --from=builder ${PREFIX} ${PREFIX}

WORKDIR ${PREFIX}

RUN ln -sf /dev/stdout ${PREFIX}/logs/access.log \
    && ln -sf /dev/stderr ${PREFIX}/logs/http-accounting.log \
    && ln -sf /dev/stderr ${PREFIX}/logs/stream-accounting.log \
    && ln -sf /dev/stderr ${PREFIX}/logs/error.log \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ADD samples/nginx-zone.conf ${PREFIX}/conf/nginx.conf
ADD samples/http-zone.conf ${PREFIX}/conf/http-zone.conf
ADD samples/stream-zone.conf ${PREFIX}/conf/stream-zone.conf

EXPOSE 8080
EXPOSE 9999
STOPSIGNAL SIGTERM
ENTRYPOINT ["./sbin/nginx", "-g", "daemon off;"]
