FROM alpine:3.20 AS builder

RUN apk add --no-cache build-base pcre-dev zlib-dev openssl-dev linux-headers curl tar

ENV NGX_VER=1.26.2

WORKDIR /src

RUN curl -sL http://nginx.org/download/nginx-${NGX_VER}.tar.gz | tar xz

WORKDIR /src/nginx-${NGX_VER}
COPY . traffic-accounting-nginx-module

RUN ./configure --prefix=/opt/nginx \
    --with-stream \
    --with-compat \
    --add-dynamic-module=traffic-accounting-nginx-module \
    && make modules

FROM scratch AS modules
COPY --from=builder /src/nginx-${NGX_VER}/objs/ngx_http_accounting_module.so /
COPY --from=builder /src/nginx-${NGX_VER}/objs/ngx_stream_accounting_module.so /
