FROM alpine:3.18 AS builder

RUN apk add --no-cache gcc make pcre-dev zlib-dev openssl-dev linux-headers curl tar

ENV NGX_VER 1.26.2
ENV WORKDIR /src
ENV NGX_SRC_DIR ${WORKDIR}/nginx-${NGX_VER}

WORKDIR ${WORKDIR}

RUN curl -sL http://nginx.org/download/nginx-${NGX_VER}.tar.gz | tar xz

WORKDIR ${NGX_SRC_DIR}
COPY . traffic-accounting-nginx-module

RUN ./configure --prefix=/opt/nginx \
    --with-stream \
    --with-compat \
    --add-dynamic-module=traffic-accounting-nginx-module \
    && make modules

FROM scratch AS modules
COPY --from=builder ${NGX_SRC_DIR}/objs/ngx_http_accounting_module.so /
COPY --from=builder ${NGX_SRC_DIR}/objs/ngx_stream_accounting_module.so /
