load_module modules/ngx_http_accounting_module.so;
worker_processes 1;
error_log /dev/stderr notice;
pid /tmp/nginx.pid;
events { worker_connections 1024; }

stream {
    accounting on;
    accounting_interval 99999;
    accounting_id 'STREAM';
    accounting_log /dev/stdout;
    server { listen 9090; }
}
