accounting on;
accounting_interval 5;
accounting_perturb off;
accounting_period_reset none;
accounting_id 'HTTP';
accounting_log logs/http-accounting.log;
accounting_zone http_accounting_zone 1m;

server {
    listen       8080;
    server_name  localhost;

    location / {
        return 200 '';
        accounting_id $uri;
    }

    location /index {
        alias  html;
        index  index.html index.htm;
        accounting_id "INDEX";
    }
}
